### ISSUE TITLE
Doesn't compile with nix >= 0.4.0

### ISSUE THREAD

**Issue by eternaleye** [agrover/devicemapper-rs#1]
nix 0.4.0 contained a rewrite of ioctl handling, which breaks this crate. Might be worth uploading a revbump that makes the dep < 0.4.0, or using the new API.

**Comment by agrover** [comment]
I thought I did, nix = "0.3.9" in Cargo.toml isn't how to do it?

**Comment by eternaleye** [comment]
I'm seeing contradictory info about that in various places, but empirically, when I tried to build something with a devicemapper dep, it pulled in nix 0.4.1 :disappointed:

I mean, the Cargo docs talk about deps being "semver compatible" and then immediately move on to caret deps, which are *described* as doing the right thing, but it doesn't come out and say that plain deps are caret deps.

In several *tickets* on Cargo it *is* said that cargo defaults to caret deps, but empirically, they seem not to be.

Setting your dep explicitly to ">= 0.3.9 < 4.0" works,  however. Despite it being ugly, and how it ought to be unnecessary.

**Comment by agrover** [comment]
`nix = "=0.3.9"` seems to work for me on nightly, how about you?

**Comment by eternaleye** [comment]
LGTM
