### ISSUE TITLE
Chops off the first 4 characters of the device name when listing

### ISSUE THREAD

**Issue by eternaleye** [agrover/devicemapper-rs#2]
Occurs on Linux 4.2.2 on x86_64:

```
eternaleye@Arkadios ~/Code/rust/rdmsetup $ sudo dmsetup ls
luks-3b1cd3b0-faf0-468b-849c-89d547d7021a       (251:0)
pool-swap       (251:1)
pool-root       (251:2)
eternaleye@Arkadios ~/Code/rust/rdmsetup $ sudo ./target/debug/rdmsetup
-3b1cd3b0-faf0-468b-849c-89d547d7021a   (251:0)
-swap   (251:1)
-root   (251:2)
```

```rust
extern crate devicemapper;

use devicemapper::DM;

fn main() {
    for (s, d) in DM::new().unwrap().list_devices().unwrap() {
        println!("{}\t({}:{})", s, d.major, d.minor);
    }
}
```

**Comment by eternaleye** [comment]
I wonder if something's being sized under the assumption that the offsets into the buffer are pointer-sized, when they're hard-set as 32bit? If so, then it'd offset by an extra 32bits on x86_64, which is four bytes.

**Comment by agrover** [comment]
I'd love some help :smile: I just pushed some still-buggy code I've been working on to better handle BUFFER_FULL_FLAG and reduce duplicated code in each method's implementation. but it appears to have broken a lot of stuff. I saw the off-by-4 thing and it has to do with Rust padding structs from what I can see. It fixed list_devices().

Will keep hacking, but please feel free to jump in with theories, insights, or PRs :smiley:

**Comment by agrover** [comment]
Working for me now, closing. Please feel free to reopen or open a fresh issue if new issues are discovered, thanks.
